language: php

sudo: false

php:
- 5.4
- 5.5
- 5.6
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.0 WP_MULTISITE=0
- WP_VERSION=3.9.2 WP_MULTISITE=0

matrix:
  exclude:
    - php: hhvm
      env: WP_VERSION=3.9.2 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=0

before_install:
  - git submodule update --init --recursive

install:
  - composer install

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- phpunit

after_success:
  - make build
  # add build number to version
  - sed -i.bak "s/\(Version:.*\)/\1.build$TRAVIS_BUILD_NUMBER/" dist/podlove.php
  - rm -f dist/podlove.php.bak
  - zip -r latest.zip dist
  - curl --ftp-create-dirs -T latest.zip -u $FTP_USER:$FTP_PASSWORD ftp://eric.co.de/files/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/

notifications:
  slack: $SLACK_TOKEN
